package myjava;

import java.util.Scanner;
public class Exchange {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("Enter a number");	//	Here we are assigning 256 for an example............
		Scanner sc = new Scanner(System.in);
		int num = sc.nextInt();
		int num1 = num;
		int onum = num;
		int rnum, count = 0;
		System.out.println("Printinng numbers you have entered at the begininng:- ");
		System.out.println(num);
		
		//	main programs goes here............
		while(num > 0) {
			num = num / 10;
			count++;	//	count  = 3 for 256......
//			System.out.println(num);
		}
		int lnum = num1 % 10;	//	last number declaration........
//		System.out.println(lnum);	//	prints 6......
		
		int fnum = num1 / (int) Math.pow(10, count - 1);	//	first number declaration........
//		System.out.println(fnum);	//	prints 2........
		
		rnum = lnum * (int) Math.pow(10, count - 1);	//	prints 600............
		rnum = rnum + onum % (int) Math.pow(10, count -1);	//	prints 656.......
		System.out.println(rnum+ " =>> first number");	//	prints 656.........
		rnum = rnum - lnum;	//	prints 650.......
		System.out.println(rnum+ " =>> second number");	//	prints 650.....
		rnum = rnum + fnum;	//	prints 652........
		System.out.println(rnum+ " =>> third number");	//	prints 652........
		
		//	Swapping the first number and last number with the each other...........
		System.out.println("The reveresd number is " +rnum+ ".");	//	prints 652......
		

	}

}
